//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf_DataBase_Hostel_App.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckInOut
    {
        public int ID_Ch { get; set; }
        public Nullable<int> ID_Stud { get; set; }
        public Nullable<System.DateTime> Date_In { get; set; }
        public Nullable<System.DateTime> Date_Out { get; set; }
    
        public virtual Students Students { get; set; }
    }
}
