//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf_DataBase_Hostel_App.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Bobrovski_4IS1_MyDataBase_HostelEntities : DbContext
    {
        public Bobrovski_4IS1_MyDataBase_HostelEntities()
            : base("name=Bobrovski_4IS1_MyDataBase_HostelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CheckInOut> CheckInOut { get; set; }
        public virtual DbSet<Exemptions> Exemptions { get; set; }
        public virtual DbSet<Pays> Pays { get; set; }
        public virtual DbSet<Prices> Prices { get; set; }
        public virtual DbSet<Rooms> Rooms { get; set; }
        public virtual DbSet<Students> Students { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
