//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf_DataBase_Hostel_App.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prices
    {
        public int ID_Price { get; set; }
        public Nullable<decimal> Pr_Sum { get; set; }
        public Nullable<System.DateTime> Pr_Date { get; set; }
    }
}
